version: '3.8'

services:
  bot:
    build: .
    container_name: cop
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - cop-net
    restart: unless-stopped
    ports:
      - "3000:3000" 

  db:
    image: postgres:16
    container_name: cop-db
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - cop-net
    restart: unless-stopped

volumes:
  db-data:

networks:
  cop-net:
