version: '3.8'

services:
  bot:
    build: .
    container_name: cop
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - cop-net
    restart: unless-stopped

  db:
    image: mariadb:10.5
    container_name: cop-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - cop-net
    restart: unless-stopped

volumes:
  db-data:

networks:
  cop-net:
